#### CGF create or replace item ###
- name: "Get {{ request_name }}"
  uri:
    url: "{{ request_url }}{{ request_path }}/{{ request_name }}"
    method: GET
    timeout: 60
    headers:
      Content-Type: "application/json"
      X-API-Token: "{{ request_token }}"
    status_code: 200
    validate_certs: False
  ignore_errors: True
  register: result
  until: result.status != -1
#- debug:
#    msg: "{{result}}"

- name: Create "{{ request_name }}"
  when: result is failed
  uri:
    url: "{{ request_url }}{{ request_path }}"
    method: POST
    timeout: 60
    headers:
      Content-Type: "application/json"
      X-API-Token: "{{ request_token }}"
    body: "{{ request_body }}"
    body_format: json
    status_code: 204
    validate_certs: False
  register: result
  until: result.status != -1
- debug:
    msg: "{{result}}"

- name: "Replace {{ request_name }}"
  when: "'skipped' in result"
  uri:
    url: "{{ request_url }}{{ request_path }}/{{ request_name }}"
    method: PUT
    timeout: 60
    headers:
      Content-Type: "application/json"
      X-API-Token: "{{ request_token }}"
    body: "{{ request_body }}"
    body_format: json
    status_code: 204
    validate_certs: False
  register: result
  until: result.status != -1

